### ISSUE TITLE
Images get cut off on mobile

### ISSUE THREAD

**Issue by Tyler-Hilbert** [Tyler-Hilbert/2024-Going-GitHub-Green-Competition#10]
![Screenshot_20240122_134446_Samsung Internet](https://github.com/Tyler-Hilbert/2024-Going-GitHub-Green-Competition/assets/6968707/2c3ca64a-cc56-4e36-b9bc-0fdfc86db090)

@daishadavis you'll probably have to use the sm: or md: breakpoints somehow, but it may be similar to the disappearing navbar

**Comment by daishadavis** [comment]
@Tyler-Hilbert I'll fix it

**Comment by daishadavis** [comment]
@Tyler-Hilbert Did you give me collaboration access already?

**Comment by Tyler-Hilbert** [comment]
> @Tyler-Hilbert Did you give me collaboration access already?

yes
