### ISSUE TITLE
Put this on your GitHub, contestant

### ISSUE THREAD

**Issue by Tyler-Hilbert** [Tyler-Hilbert/2024-Going-GitHub-Green-Competition#11]
[![](https://ossrank.com/widget/911876)](https://ossrank.com/c/911876)

`[![](https://ossrank.com/widget/911876)](https://ossrank.com/c/911876)`

**Comment by daishadavis** [comment]
@Tyler-Hilbert This is awesome where do I put it

**Comment by Tyler-Hilbert** [comment]
Anywhere there's markdown.
Try creating a daishadavis.github.io repo and then put it in a file called readme.md
