### ISSUE TITLE
Add the css back in

### ISSUE THREAD

**Issue by Tyler-Hilbert** [Tyler-Hilbert/2024-Going-GitHub-Green-Competition#16]
@daishadavis do you think you can add the CSS back in, I think it accidentally got deleted.

**Comment by daishadavis** [comment]
@Tyler-Hilbert yea I'm on it

**Comment by daishadavis** [comment]
@Tyler-Hilbert Tailwind config has been added

**Comment by Tyler-Hilbert** [comment]
@daishadavis nailed it
https://github.com/Tyler-Hilbert/2024-Going-GitHub-Green-Competition/commit/a4d4c1dbff187e8846bc87500ad2b2a2ff6613b0
