### ISSUE TITLE
Add Tembo back

### ISSUE THREAD

**Issue by Tyler-Hilbert** [Tyler-Hilbert/2024-Going-GitHub-Green-Competition#17]
Can you add Tembo back to the competition?

**Comment by daishadavis** [comment]
@Tyler-Hilbert Who's tembo?

**Comment by Tyler-Hilbert** [comment]
https://twitter.com/SoftwareTyler/status/1756356493681607019

lol look in the git history for a time when tembo was included

**Comment by daishadavis** [comment]
@Tyler-Hilbert All done
