### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by Tyler-Hilbert** [Tyler-Hilbert/2024-Going-GitHub-Green-Competition#18]
Can you add a .gitignore so .DS_Store doesn't end up in repo.
Here's an example:
https://github.com/Tyler-Hilbert/python_work/blob/main/.gitignore

**Comment by daishadavis** [comment]
@Tyler-Hilbert  done

**Comment by Tyler-Hilbert** [comment]
You have to delete the .DS_Store also....
`git rm .DS_Store`

**Comment by daishadavis** [comment]
@Tyler-Hilbert Now its done

**Comment by Tyler-Hilbert** [comment]
Awesome! And here's a pro tip, press "Close" and include a link to the commit when you fix an issue.

https://github.com/Tyler-Hilbert/2024-Going-GitHub-Green-Competition/commit/00f4ebdff2de3b741d3406bd4cddf7e1de622bc2
